name = "Beyond Adventures"
author = "Sajmon"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf8ddd55914540249dd8e76b0b70362484287222dc90250eee828446bdad1f3e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
