#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 29 10:55:28 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=Visual-Vibrance-v0.3.5a.zip
